artifacts_root: artifacts

data_ingestion:
 root_dir: artifacts/data_ingestion
 source_URL: https://github.com/someshnaman/End_to_end_MLOPS_project_/raw/master/wine-data.zip
 local_data_file: artifacts/data_ingestion/data.zip
 unzip_dir: artifacts/data_ingestion

data_validation:
 root_dir: artifacts/data_validation
 unzip_data_dir: artifacts/data_ingestion/winequalityN.csv
 STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
 root_dir: artifacts/data_transformation
 data_path: artifacts/data_ingestion/winequalityN.csv